version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: "product-service"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - echo Fetching the exact ECR Public registry alias assigned to this account...
      - # Mengambil token alias asli dari akun AWS Anda secara otomatis tanpa hardcode
        export REGISTRY_ALIAS=$(aws ecr-public describe-registries --region us-east-1 --query "registries[0].registryAlias" --output text)
      - echo "Your official AWS ECR Public Registry Alias is: $REGISTRY_ALIAS"
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling Spring Boot application...
      - mvn clean package -DskipTests
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - echo Tagging the Docker image for ECR Public...
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$REGISTRY_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to AWS ECR Public...
      - docker push public.ecr.aws/$REGISTRY_ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
