version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "132851953521"
    AWS_REGION: "ap-southeast-1"
    IMAGE_REPO_NAME: "spring/product-service"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR Private..."
      - # Menggunakan region Singapura sesuai lokasi repositori private Anda
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_://amazonaws.com
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling Spring Boot application..."
      - mvn clean package -DskipTests
      - echo "Building the Docker image..."
      - docker build -t spring-app:latest .
      - echo "Tagging the Docker image for ECR Private..."
      - docker tag spring-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_://amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image to AWS ECR Private..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_://amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - # Membuat file manifest untuk sinkronisasi otomatis ke AWS ECS nanti
        echo "[{\"name\":\"product-service-container\",\"imageUri\":\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_://amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - appspec.yaml
    - imagedefinitions.json
